package com.design.composeNur.theme.dimensions

import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.unit.Dp
import com.design.composenur.R

@Immutable
data class NurViewDimensions(
    val view0Dp: Dp,
    val view1Dp: Dp,
    val view2Dp: Dp,
    val view3Dp: Dp,
    val view4Dp: Dp,
    val view5Dp: Dp,
    val view6Dp: Dp,
    val view8Dp: Dp,
    val view10Dp: Dp,
    val view12Dp: Dp,
    val view14Dp: Dp,
    val view15Dp: Dp,
    val view16Dp: Dp,
    val view18Dp: Dp,
    val view20Dp: Dp,
    val view21Dp: Dp,
    val view24Dp: Dp,
    val view26Dp: Dp,
    val view27Dp: Dp,
    val view28Dp: Dp,
    val view30Dp: Dp,
    val view32Dp: Dp,
    val view35Dp: Dp,
    val view40Dp: Dp,
    val view44Dp: Dp,
    val view46Dp: Dp,
    val view48Dp: Dp,
    val view52Dp: Dp,
    val view57Dp: Dp,
    val view60Dp: Dp,
    val view64Dp: Dp,
    val view68Dp: Dp,
    val view72Dp: Dp,
    val view74Dp: Dp,
    val view75Dp: Dp,
    val view76Dp: Dp,
    val view80Dp: Dp,
    val view82Dp: Dp,
    val view88Dp: Dp,
    val view90Dp: Dp,
    val view94Dp: Dp,
    val view96Dp: Dp,
    val view100Dp: Dp,
    val view102Dp: Dp,
    val view110Dp: Dp,
    val view120Dp: Dp,
    val view122Dp: Dp,
    val view125Dp: Dp,
    val view136Dp: Dp,
    val view138Dp: Dp,
    val view140Dp: Dp,
    val view150Dp: Dp,
    val view168Dp: Dp,
    val view172Dp: Dp,
    val view200Dp: Dp,
    val view210Dp: Dp,
    val view220Dp: Dp
) {
    companion object {
        @Composable
        fun fromResources() = NurViewDimensions(
            view0Dp = dimensionResource(R.dimen.view_0dp),
            view1Dp = dimensionResource(R.dimen.view_1dp),
            view2Dp = dimensionResource(R.dimen.view_2dp),
            view3Dp = dimensionResource(R.dimen.view_3dp),
            view4Dp = dimensionResource(R.dimen.view_4dp),
            view5Dp = dimensionResource(R.dimen.view_5dp),
            view6Dp = dimensionResource(R.dimen.view_6dp),
            view8Dp = dimensionResource(R.dimen.view_8dp),
            view10Dp = dimensionResource(R.dimen.view_10dp),
            view12Dp = dimensionResource(R.dimen.view_12dp),
            view14Dp = dimensionResource(R.dimen.view_14dp),
            view15Dp = dimensionResource(R.dimen.view_15dp),
            view16Dp = dimensionResource(R.dimen.view_16dp),
            view18Dp = dimensionResource(R.dimen.view_18dp),
            view20Dp = dimensionResource(R.dimen.view_20dp),
            view21Dp = dimensionResource(R.dimen.view_21dp),
            view24Dp = dimensionResource(R.dimen.view_24dp),
            view26Dp = dimensionResource(R.dimen.view_26dp),
            view27Dp = dimensionResource(R.dimen.view_27dp),
            view28Dp = dimensionResource(R.dimen.view_28dp),
            view30Dp = dimensionResource(R.dimen.view_30dp),
            view32Dp = dimensionResource(R.dimen.view_32dp),
            view35Dp = dimensionResource(R.dimen.view_35dp),
            view40Dp = dimensionResource(R.dimen.view_40dp),
            view44Dp = dimensionResource(R.dimen.view_44dp),
            view46Dp = dimensionResource(R.dimen.view_46dp),
            view48Dp = dimensionResource(R.dimen.view_48dp),
            view52Dp = dimensionResource(R.dimen.view_52dp),
            view57Dp = dimensionResource(R.dimen.view_57dp),
            view60Dp = dimensionResource(R.dimen.view_60dp),
            view64Dp = dimensionResource(R.dimen.view_64dp),
            view68Dp = dimensionResource(R.dimen.view_68dp),
            view72Dp = dimensionResource(R.dimen.view_72dp),
            view74Dp = dimensionResource(R.dimen.view_74dp),
            view75Dp = dimensionResource(R.dimen.view_75dp),
            view76Dp = dimensionResource(R.dimen.view_76dp),
            view80Dp = dimensionResource(R.dimen.view_80dp),
            view82Dp = dimensionResource(R.dimen.view_82dp),
            view88Dp = dimensionResource(R.dimen.view_88dp),
            view90Dp = dimensionResource(R.dimen.view_90dp),
            view94Dp = dimensionResource(R.dimen.view_94dp),
            view96Dp = dimensionResource(R.dimen.view_96dp),
            view100Dp = dimensionResource(R.dimen.view_100dp),
            view102Dp = dimensionResource(R.dimen.view_102dp),
            view110Dp = dimensionResource(R.dimen.view_110dp),
            view120Dp = dimensionResource(R.dimen.view_120dp),
            view122Dp = dimensionResource(R.dimen.view_122dp),
            view125Dp = dimensionResource(R.dimen.view_125dp),
            view136Dp = dimensionResource(R.dimen.view_136dp),
            view138Dp = dimensionResource(R.dimen.view_138dp),
            view140Dp = dimensionResource(R.dimen.view_140dp),
            view150Dp = dimensionResource(R.dimen.view_150dp),
            view168Dp = dimensionResource(R.dimen.view_168dp),
            view172Dp = dimensionResource(R.dimen.view_172dp),
            view200Dp = dimensionResource(R.dimen.view_200dp),
            view210Dp = dimensionResource(R.dimen.view_210dp),
            view220Dp = dimensionResource(R.dimen.view_220dp)
        )
    }
}